### ISSUE TITLE
Grisha, help me please

### ISSUE THREAD

**Issue by MrMasterBlaster** [MrMasterBlaster/Boxers#4]
I can't find the BIG bug in my huge mass of shit code. There is more bug, but some one is make fucking duplicate of "condition" in the "List<Condition>" in "AI" class. Can you fix it?

**Comment by MrMasterBlaster** [comment]
So, it's done

**Comment by SpaceDandy406** [comment]
ahahaha, sory for delay

**Comment by SpaceDandy406** [comment]
I should to come here more often
